# Generated by Django 2.0 on 2017-12-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Article publié ?'),
        ),
    ]
